### ISSUE TITLE
Diagnosis of 2D wall BC MMS test issue

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#85]
The MMS test suite is designed to allow for rapid development of new features using a symbolic algebra package to compute the sources in the DKE given a 'target' manufactured solution. For the 2D-3V version of the code with E_r =/= 0 and wall boundary conditions, the test has identified a possible issue of non-convergence with increasing resolution

Here I start to try to track down the error. I start with commit ecfa0f87bc391675b33133eb4a4c68acf20e1e4c. Running the input files
 `runs/2D-wall_cheb-with-neutrals_nel_r_1_z_2_vpa_2_vperp_2`
`runs/2D-wall_cheb-with-neutrals_nel_r_1_z_4_vpa_4_vperp_4`
`runs/2D-wall_cheb-with-neutrals_nel_r_1_z_8_vpa_8_vperp_8`
`runs/2D-wall_cheb-with-neutrals_nel_r_1_z_16_vpa_16_vperp_16`
where I increase the number of elements of all the z, v||, vperp, vz, vr, vzeta grids (for a single r point with E_r = 0) and reduce the time step in tandem, I generate the following figures (with `run_MMS_test.jl`).
[MMS_test_velocity_nelement_1D-3V-wall_cheb-updated.pdf](https://github.com/mabarnes/moment_kinetics/files/9831423/MMS_test_velocity_nelement_1D-3V-wall_cheb-updated.pdf)
[MMS_test_velocity_nelement_1D-3V-wall_cheb-updated_fields_no_Er.pdf](https://github.com/mabarnes/moment_kinetics/files/9831424/MMS_test_velocity_nelement_1D-3V-wall_cheb-updated_fields_no_Er.pdf)

These figures demonstrate declining errors in all fields, approaching machine precision. The error in the neutral density remains surprisingly high.

**Comment by mrhardman** [comment]
I have now generated a series of 2D-3V runs with a spatially 2D grid, and E_r = 0 on the wall boundaries (using commit c6867a051a4a4aa82604ca22b4b4701f561b3166 and the input files from commit bd7fd4bfc49557999f7ead27c845a9d3fb6186bf). Using a similar procedure to the 1D case, I scan in n_element of each coordinate, plus I reduce the time step at fixed (physical time) simulation length. The error fields between the numerical and symbolic moments, dfns and fields are shown below.

[MMS_test_velocity_nelement_2D-3V-wall_cheb.pdf](https://github.com/mabarnes/moment_kinetics/files/9840116/MMS_test_velocity_nelement_2D-3V-wall_cheb.pdf)
[MMS_test_velocity_nelement_2D-3V-wall_cheb_fields.pdf](https://github.com/mabarnes/moment_kinetics/files/9840117/MMS_test_velocity_nelement_2D-3V-wall_cheb_fields.pdf)

N.B. that the errors do not reduce as rapidly between n_element = 4, 6 and between n_element = 2, 4. This may indicate a problem with the radial coordinate implementation, separate from the wall boundary condition. I was unable to go to n_element = 8 due to memory errors. 

I include also figures showing the symbolic (E_r^sym, E_z^sym) and numerical (E_r, E_z) radial and axial electric fields, to demonstrate that E_r = 0 indeed holds on the boundary, and that the electric fields are indeed behaving reasonably well in this case.
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er_sym_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9840161/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er_sym_vs_r_z.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9840162/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er_vs_r_z.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez_sym_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9840163/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez_sym_vs_r_z.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9840164/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez_vs_r_z.pdf)

**Comment by mrhardman** [comment]
Having inspected cases with E_r = 0 at the wall boundary and found largely reasonable behaviour, I now report a case with E_r /= 0 on the wall boundary. Using the input files 
`2D-wall_cheb-with-neutrals_nel_r_2_z_2_vpa_2_vperp_2.toml`
`2D-wall_cheb-with-neutrals_nel_r_4_z_4_vpa_4_vperp_4.toml`
`2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6.toml`
with `nzero` = `nplus` = `nminus = 1.0 + 0.05*sin(2.0*pi*r/Lr)` in `manufactured_solns.jl`. Carrying out the MMS test, scanning in nelement in all coordinate grids, we find the following error behaviours:
[MMS_test_velocity_nelement_2D-3V-wall_cheb.pdf](https://github.com/mabarnes/moment_kinetics/files/9851527/MMS_test_velocity_nelement_2D-3V-wall_cheb.pdf)
[MMS_test_velocity_nelement_2D-3V-wall_cheb_fields.pdf](https://github.com/mabarnes/moment_kinetics/files/9851529/MMS_test_velocity_nelement_2D-3V-wall_cheb_fields.pdf)

Note that the error in F_i, n_i, F_n, n_n, and phi are not bad, although the rate at which the error is reducing appears to be falling off with increasing nelement. By itself, this would indicate potential problems with the numerical implementation. However, inspecting the errors of Er and Ez, we see that these quantities hardly become closer to the target solutions as nelement increases. It is interesting to view phi, Er and Ez along a cut in z (at fixed r), and at the wall (fixed z) as function of r. These plots are given here for numerical (num) and target symbolic (sym) solutions:
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9851556/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er.r.z_wall._vs_r.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9851557/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Er.r0.z._vs_z.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9851558/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez.r.z_wall._vs_r.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9851559/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_Ez.r0.z._vs_z.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_phi(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9851560/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_phi.r.z_wall._vs_r.pdf)
[2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_phi(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9851561/2D-wall_cheb-with-neutrals_nel_r_6_z_6_vpa_6_vperp_6_phi.r0.z._vs_z.pdf)
Note that phi appears to be captured well with 6 elements, but Ez and Er suffer from errors. These are particularly noticeable at z_wall, where they manifest themselves in oscillations in r. For Ez, the numerical solution and symbolic targets are close as a function of z at the fixed r chosen, whereas Er appears to suffer from sharp structures at the wall boundary.

**Comment by mrhardman** [comment]
To investigate this issue further, I have performed more comprehensive tests using the 'periodic' boundary conditions option and associated MMS tests. Using commit 1cb351978534d5ad21640559c8e74c163680301d and the input files 
`2D-sound-wave_cheb_ion_only_nel_r_2_z_2_vpa_2_vperp_2.toml`
`2D-sound-wave_cheb_ion_only_nel_r_4_z_4_vpa_4_vperp_4.toml`
`2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8.toml`
I have tested the time advance, spatial advection, and parallel acceleration operators, as well as the field solve. 

The headline MMS error plots are below:
[MMS_test_nelement_2D-sound-wave_cheb_ions_only.pdf](https://github.com/mabarnes/moment_kinetics/files/9887749/MMS_test_nelement_2D-sound-wave_cheb_ions_only.pdf)
[MMS_test_nelement_2D-sound-wave_cheb_ions_only_fields.pdf](https://github.com/mabarnes/moment_kinetics/files/9887750/MMS_test_nelement_2D-sound-wave_cheb_ions_only_fields.pdf)

For nelement = 8 the target (sym) and output solutions are visually similar, e.g., looking at the potential, we have the following plots.
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi_sym_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9887753/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi_sym_vs_r_z.pdf)
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9887754/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi_vs_r_z.pdf)

However, whilst the fields appear smooth, there is some evidence of imperfect behaviour. The errors in the plots above are not negligible, and may be larger than expected given the anticipated spectral accuracy of the scheme. We can see the potential hallmark of these errors by inspecting the electric fields and potentials as fns of r and z. Note that the 'wall' is not a special point in these periodic simulations. The errors are most easily visible in the plots of Ez(r) and Er(z), where they appear as an offset between the numerical and symbolic solutions. 

[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Er(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kineti
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Ez(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9887781/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Ez.r.z_wall._vs_r.pdf)
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9887782/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi.r.z_wall._vs_r.pdf)
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Er(r,z_wall)_vs_r.pdf](https://github.com/mabarnes/moment_kinetics/files/9887783/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Er.r.z_wall._vs_r.pdf)
cs/files/9887778/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Er.r0.z._vs_z.pdf)
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Ez(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9887779/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_Ez.r0.z._vs_z.pdf)
[2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi(r0,z)_vs_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9887780/2D-sound-wave_cheb_ion_only_nel_r_8_z_8_vpa_8_vperp_8_phi.r0.z._vs_z.pdf)

I note that this case above ran with ions only. I am currently experiencing difficulties (DomainError in sqrt of ion pressure/density, indicating negative ion dfn) in running this case with n_neutral_species = 1, for reasons that are not yet clear. @mabarnes @johnomotani Possible evidence of problems with the core algorithm/bugs in upgrade to 2D fields.

**Comment by mrhardman** [comment]
@mabarnes @johnomotani Clarifying the final comment, I find that I receive an unpredictable DomainError at line 598 of time_advance.jl for nelement = 6 in the sound wave MMS test. You can find the .toml and output files here.
[sound-wave_6.zip](https://github.com/mabarnes/moment_kinetics/files/9893371/sound-wave_6.zip)
I notice that the timestep which the error occurrs on is not exactly the same each time. It is sometimes at nstep = 6, sometimes nstep = 8 etc. Perhaps this indicates an error that depends on the state of the MPI?

I can say that in the timestep before the errors occur, there is nothing to indicate that the ion dfn is about to go negative. For example, running to nstep =6, we have the following outputs in the r_z plane.
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_dens_vs_r_z_ion.pdf](https://github.com/mabarnes/moment_kinetics/files/9893372/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_dens_vs_r_z_ion.pdf)
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_dens_vs_r_z_neutral.pdf](https://github.com/mabarnes/moment_kinetics/files/9893373/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_dens_vs_r_z_neutral.pdf)
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_Er_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9893374/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_Er_vs_r_z.pdf)
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_Ez_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9893375/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_Ez_vs_r_z.pdf)
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_phi_vs_r_z.pdf](https://github.com/mabarnes/moment_kinetics/files/9893376/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_phi_vs_r_z.pdf)
We can also look at the time traces of the error on the ion distribution function dfni -- these also do not seem to be bad enough to suggest that the simulation is about to break.
[2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_pdf_norm_vs_t_ion.pdf](https://github.com/mabarnes/moment_kinetics/files/9893385/2D-sound-wave_cheb_nel_r_6_z_6_vpa_6_vperp_6_pdf_norm_vs_t_ion.pdf)

I have tried varying the number of elements of the neutral species velocity space grids to 5 and 7, in the hope of catching an out of bounds error (perhaps the ions access neutral information, or vice versa) but no error was triggered.

**Comment by johnomotani** [comment]
Sorry I haven't had time to finish working on #67, which should help prevent shared memory errors.

For now, can you try running the suspicious case for a couple of steps (`nstep = 2` maybe) while adding the flags: `--compiled-modules=no` to julia (before the `run_moment_kinetics.jl` or whichever script you're running); and `--debug 2` (after the script)? Those flags should mean an error is raised if there are any incorrect shared-memory accesses (probably good to merge #87 first!).

**Comment by johnomotani** [comment]
Actually, what I just suggested may not work. I've been having trouble with `--compiled-modules=no`. I had a problem using that flag with Symbolics.jl before, and now seem to be getting a lot of errors. Not sure if it is the same issue...

**Comment by johnomotani** [comment]
I found one shared-memory problem, now fixed in #87.

@mrhardman it may still be worth switching on the debugging for your run, as the errors may only show up on a certain number of processes (I tested with 4). The workaround for the `--compiled-modules` issue for the moment is to hard-code the `debug_level` in `debugging.jl`, e.g. temporarily change
https://github.com/mabarnes/moment_kinetics/blob/7975a26ce44f790f2c53e44f34a5ba079c347e74/src/debugging.jl#L44
to
```julia
const _debug_level = 2
```

**Comment by mrhardman** [comment]
@johnomotani I have now merged your MPI fixes via cherry pick into the 'experimental' branch `radial-vperp-standard-DKE-with-neutrals-pdf-animations`.

I do see a great deal of output when setting `_debug_level =2` -- currently trying to decode what are errors.

**Comment by johnomotani** [comment]
I've been looking at the convergence of the integral of a function like
```math
f(x) = \left\{ \begin{array}{ll}
0  & x < x_0 \\
(x-x_0)^n  & x > x_0
\end{array} \right.
```
The results don't look great - the convergence seems to depend on the order of the polynomial $n$, rather than the order of the numerical scheme. I guess when they say it converges for 'smooth functions' they really mean it!

The script I've used is: 
[integrate-piecewise-test.txt](https://github.com/mabarnes/moment_kinetics/files/9903686/integrate-piecewise-test.txt)
(suffix .txt instead of .jl so that GitHub will upload it)

Results plotted below. Sorry the plots are busy and the colours repeat, but I think the point is still there...
With Chebyshev integration:
The different lines are different `ngrid` values, so different polynomial orders within each element. The upshot is `ngrid` seems to make little difference, as long as it is high enough to represent a polynomial of order $n$. The black dotted trend-line is $dx^{n+1}$ where $dx=$`x.L/x.n`. The results are pretty noisy, I guess because this is the error on just a single number (the integral) rather than many grid points of a function, so it can be better than expected by chance. The envelope of the errors (regardless of `ngrid`) seems to be well fitted by the trend line though.

If these were smooth polynomial functions (of order $n$), rather than piecewise ones, the integration would be exact to machine precision, as long as `ngrid` is high enough.

![chebyshev_pseudospectral_n1](https://user-images.githubusercontent.com/3958036/199076986-95210864-fbeb-484e-9ccf-7fdddef0f099.png)
![chebyshev_pseudospectral_n2](https://user-images.githubusercontent.com/3958036/199077055-4ee87482-7597-4db6-9bff-430b66d7356d.png)
![chebyshev_pseudospectral_n3](https://user-images.githubusercontent.com/3958036/199077068-76dd9da4-8fb0-44c9-86b4-0801390aa46a.png)
![chebyshev_pseudospectral_n4](https://user-images.githubusercontent.com/3958036/199077091-c2d669e9-00cc-423a-af06-1168f7d91d26.png)
![chebyshev_pseudospectral_n5](https://user-images.githubusercontent.com/3958036/199077107-c2b75e8e-b33c-42b0-b3ea-f5881b400cf2.png)
![chebyshev_pseudospectral_n6](https://user-images.githubusercontent.com/3958036/199077127-537628b4-72ba-412e-b092-771fbb386fdf.png)
![chebyshev_pseudospectral_n7](https://user-images.githubusercontent.com/3958036/199077170-a67f31be-2874-49a4-bd04-6f81d63c1f26.png)
![chebyshev_pseudospectral_n8](https://user-images.githubusercontent.com/3958036/199077187-ebe59639-9e59-411a-88f7-43b18e25e0d1.png)

With finite difference integration (Simpson's rule), the trend line is $dx^{n+1}$ for $n\leq3$ and $dx^4$ for $n\geq 3$.
![finite_difference_n1](https://user-images.githubusercontent.com/3958036/199078313-c449522b-66a6-4438-8e04-cb727e095e11.png)
![finite_difference_n2](https://user-images.githubusercontent.com/3958036/199078336-a23232bc-8952-47e6-9916-2ae0aa6cb026.png)
![finite_difference_n3](https://user-images.githubusercontent.com/3958036/199078339-549d8782-752b-4935-9549-293f85430cbb.png)
![finite_difference_n4](https://user-images.githubusercontent.com/3958036/199078340-49d91481-1e39-4f20-bfea-8623a017f00f.png)
![finite_difference_n5](https://user-images.githubusercontent.com/3958036/199078343-58cbfb9b-7935-4ab8-a019-fe6e552f6802.png)
![finite_difference_n6](https://user-images.githubusercontent.com/3958036/199078347-c757fe27-3f0d-40ac-b82a-53696a3035f8.png)
![finite_difference_n7](https://user-images.githubusercontent.com/3958036/199078350-85b90246-3dbe-48a1-aad8-d8bddcf02383.png)
![finite_difference_n8](https://user-images.githubusercontent.com/3958036/199078351-596629c9-0472-4a58-a01d-7e662842cec1.png)

**Comment by mrhardman** [comment]
Exploring the MPI errors further on Marconi, I attempted to ensure that the MPI.jl module used the appropriate system libraries (see https://juliaparallel.org/MPI.jl/stable/configuration/). I was able to get this to (partially) work with Julia 1.7.2 compatible libraries. See radial-vperp-standard-DKE-with-neutrals-Julia-1.7.2 commit 70f6e6376c2aadf2a18f69c510823c336f4dea20.

Running the sound wave MMS input file with nelement = 6, we find the following error output.

[mk6_bug.zip](https://github.com/mabarnes/moment_kinetics/files/9912262/mk6_bug.zip)

**Comment by mabarnes** [comment]
I don't quite understand what is being plotted on the horizontal axis in the integral plots above.  Seems like the polynomial order and the number of grid points is being held fixed, so is L changing in order to make dx change?

As having non-smooth functions destroys spectral accuracy, perhaps we should see if we can develop a scheme for placing the discontinuous derivative at an element boundary?  This could be done by changing our vpa variable or by having an adaptive mesh in vpa.  Assuming the shift in the special vpa point were smoothly varying in time, the latter approach may only require interpolation within 1-2 vpa elements at each time step...

**Comment by johnomotani** [comment]
Sorry - the x-axis is `dx = x.L/x.n = x.L/(x.nelement*(x.ngrid-1) + 1)`, and `nelement` is the parameter that is varied along each individual line.

Some kind of adaptive scheme to put the discontinuous derivative on an element boundary does sound like a good idea.
I do also still like the idea of smoothing out the discontinuity somehow (e.g. some tiny amount of collisions?), but don't have any good ideas how to do this at the moment...
